version: '3.5'
services:

  sbe:
    build: SBE_docker
    hostname: sbe.${domain}
    container_name: sbe.${domain}
    restart: unless-stopped
    privileged: true
    volumes:
      - ${sshdir}:/root/.ssh
      - ./:/opt/SBE
      - ${reportsdir}:/tmp/SBE_reports
      - ${sbdir}:/tmp/SBE_settings
    networks:
      - debian-net

networks:
  debian-net:
    ipam:
      config:
        - subnet: 172.23.238.0/24
