services:
  # Backup Service
  sbe-backup:
    build:
      context: .
      dockerfile: ./backup/Dockerfile
    image: sbe-backup:${DOMAIN:-example}
    container_name: sbe.backup.${DOMAIN:-example.com}
    hostname: sbe.backup.${DOMAIN:-example.com}
    restart: unless-stopped
    privileged: true
    volumes:
      - ${SSH_DIR:-~/.ssh}:/root/.ssh
      - ./:/opt/SBE
      - ${REPORTS_DIR:-/var/SBE/reports}:${REPORTS_DIR:-/var/SBE/reports}
      - ${SETTINGS_DIR:-/var/SBE/settings}:${SETTINGS_DIR:-/var/SBE/settings}
      # msmtprc is now generated dynamically from template and .env
      - /etc/localtime:/etc/localtime:ro
    environment:
      - KEYSERVER_HOST=${KEYSERVER_HOST:-https://sbe.keyserver.example.com:8443}
      - KEYSERVER_API_KEY=${KEYSERVER_API_KEY:-changeme}
      - REPORTS_DIR=${REPORTS_DIR:-/var/SBE/reports}
      - SETTINGS_DIR=${SETTINGS_DIR:-/var/SBE/settings}
      - MAIL_RECIPIENT=${MAIL_RECIPIENT:-admin}
      - MAX_SIMULTANEOUS_BACKUPS=${MAX_SIMULTANEOUS_BACKUPS:-2}
      - DOMAIN=${DOMAIN:-example.com}
    networks:
      - backup-net
    depends_on:
      - sbe-keyserver

  # Key Server Service
  sbe-keyserver:
    build: ./keyserver
    image: sbe-keyserver:${DOMAIN:-example}
    container_name: sbe.keyserver.${DOMAIN:-example.com}
    hostname: sbe.keyserver.${DOMAIN:-example.com}
    restart: unless-stopped
    environment:
      - API_KEY=${KEYSERVER_API_KEY:-changeme}
      - POSTGRES_USER=${POSTGRES_USER:-sbeuser}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-changepassword}
      - POSTGRES_DB=${POSTGRES_DB:-sbe_keyserver}
      - DOMAIN=${DOMAIN:-example.com}
    volumes:
      - keyserver-data:/data
      - ./keyserver/config/certs:/app/config/certs
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "${KEYSERVER_PORT:-8443}:8443"
    networks:
      - backup-net
    depends_on:
      - sbe-keyserver-db
    command: ["/wait-for-it.sh", "sbe-keyserver-db:5432", "--timeout=40", "--", "python3", "app.py"]

  # Key Server Database
  sbe-keyserver-db:
    image: postgres:14-alpine
    container_name: sbe.keyserver.db.${DOMAIN:-example.com}
    hostname: sbe.keyserver.db.${DOMAIN:-example.com}
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-sbeuser}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-changepassword}
      - POSTGRES_DB=${POSTGRES_DB:-sbe_keyserver}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - backup-net

networks:
  backup-net:
    name: backup-net-${DOMAIN:-example}

volumes:
  postgres-data:
    name: postgres-data-${DOMAIN:-example}
  keyserver-data:
    name: keyserver-data-${DOMAIN:-example}
